name = "FUNC"
version = "0.0.2"
pack-format = "packwiz:1.1.0"

[index]
file = "index.toml"
hash-format = "sha256"
hash = "e59dfbea5465b5e2fb07d50e317f320afb6cd8d08c76986f0fd1eb453d346c7a"

[versions]
minecraft = "1.21.1"
neoforge = "21.1.142"
